The purpose of this project is to implement field coverage method. 
controller: pure pursuit
robot model: ackermann system
trace type: pi turn, omega turn, no fish tail.  

Filed are generated by points. Order to cover points is generated by GA method. 
